/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.g6_clienteservidorproyecto;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asanc
 */
public class AgregarArticulos extends javax.swing.JFrame {

    /**
     * Creates new form AgregarArticulos
     */
    public AgregarArticulos() {
        initComponents();
    this.setLocationRelativeTo(null);
    cargarArticulosTabla();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTArticulos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTcodigoAbuscar = new javax.swing.JTextPane();
        lbl_titulo1 = new javax.swing.JLabel();
        jBagregarCodigoCarrito = new javax.swing.JButton();
        jBsalirAlMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lbl_titulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_titulo.setForeground(new java.awt.Color(0, 0, 0));
        lbl_titulo.setText("Artículos disponibles");

        jTArticulos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Precio", "Nombre", "Descripción", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTArticulos);

        jTcodigoAbuscar.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(jTcodigoAbuscar);

        lbl_titulo1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_titulo1.setForeground(new java.awt.Color(0, 0, 0));
        lbl_titulo1.setText("Código del producto para agregar al carrito");

        jBagregarCodigoCarrito.setText("Agregar al carrito");
        jBagregarCodigoCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBagregarCodigoCarritoActionPerformed(evt);
            }
        });

        jBsalirAlMenu.setText("Salir");
        jBsalirAlMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalirAlMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(lbl_titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jBagregarCodigoCarrito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 210, Short.MAX_VALUE)
                .addComponent(jBsalirAlMenu)
                .addGap(32, 32, 32))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(382, 382, 382)
                .addComponent(lbl_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lbl_titulo)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_titulo1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBagregarCodigoCarrito)
                        .addComponent(jBsalirAlMenu)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void cargarArticulosTabla(){
        ArrayList<Objeto> arrayListaArticulos = new ArrayList<Objeto>();
        arrayListaArticulos = Objeto.obtenerArticulos();
        DefaultTableModel contenidoTabla = (DefaultTableModel) jTArticulos.getModel();
         
         Object rowDeTabla[] = new Object [5];
         
           if (arrayListaArticulos!=null){
            
            for (int i=0; i<arrayListaArticulos.size();i++){
                
                rowDeTabla[0]= arrayListaArticulos.get(i).getCodigoArticulo();
                rowDeTabla[1]= arrayListaArticulos.get(i).getPrecioArticulo();
                rowDeTabla[2]= arrayListaArticulos.get(i).getNombreArticulo();
                rowDeTabla[3]= arrayListaArticulos.get(i).getDescripcionArticulo();
                rowDeTabla[4]= arrayListaArticulos.get(i).getCantidadArticulo();
                contenidoTabla.addRow(rowDeTabla);
                
            }
            jTArticulos.setModel(contenidoTabla);
            
        }else{
            JOptionPane.showMessageDialog(null,"No existen artículos en el sistema");
        }
         
        
    }
    
    
    
    private void jBsalirAlMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalirAlMenuActionPerformed
this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jBsalirAlMenuActionPerformed

    private void jBagregarCodigoCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBagregarCodigoCarritoActionPerformed
String codigoItem = jTcodigoAbuscar.getText();
Objeto.agregarAlCarrito(codigoItem);
jTcodigoAbuscar.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_jBagregarCodigoCarritoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarArticulos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarArticulos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBagregarCodigoCarrito;
    private javax.swing.JButton jBsalirAlMenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTArticulos;
    private javax.swing.JTextPane jTcodigoAbuscar;
    private javax.swing.JLabel lbl_titulo;
    private javax.swing.JLabel lbl_titulo1;
    // End of variables declaration//GEN-END:variables
}
