/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto.g6_clienteservidorproyecto;
import java.awt.Color;
import javax.swing.JOptionPane;
/**
 *
 * @author asanc
 */
public class frm_Administrador_Inicio extends javax.swing.JFrame {

    /**
     * Creates new form frm_Administrador_Inicio
     */
    public frm_Administrador_Inicio() {
        initComponents();
        getContentPane().setBackground(Color.white);
    this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_bienvenido = new javax.swing.JLabel();
        lbl_vamos = new javax.swing.JLabel();
        lbl_usuario = new javax.swing.JLabel();
        txt_usuario_Administrador = new javax.swing.JTextField();
        lbl_contraseña = new javax.swing.JLabel();
        txt_password_Administrador = new javax.swing.JPasswordField();
        btn_IngresarUsuario = new javax.swing.JButton();
        btn_ingresarAdministrador = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_bienvenido.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_bienvenido.setText("Bienvenido");

        lbl_vamos.setText("Ingresar sesión como administrador");

        lbl_usuario.setText("Usuario");

        lbl_contraseña.setText("Contraseña");

        txt_password_Administrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_password_AdministradorActionPerformed(evt);
            }
        });

        btn_IngresarUsuario.setBackground(new java.awt.Color(0, 102, 204));
        btn_IngresarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btn_IngresarUsuario.setText("¿Ingresar como usuario?");
        btn_IngresarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_IngresarUsuarioMouseClicked(evt);
            }
        });
        btn_IngresarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IngresarUsuarioActionPerformed(evt);
            }
        });

        btn_ingresarAdministrador.setBackground(new java.awt.Color(0, 102, 204));
        btn_ingresarAdministrador.setForeground(new java.awt.Color(255, 255, 255));
        btn_ingresarAdministrador.setText("Ingresar");
        btn_ingresarAdministrador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ingresarAdministradorMouseClicked(evt);
            }
        });
        btn_ingresarAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarAdministradorActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contains/Subtract.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(lbl_vamos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_password_Administrador, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_contraseña)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbl_bienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(143, 143, 143))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txt_usuario_Administrador, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(86, 86, 86)))
                        .addComponent(lbl_usuario))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_ingresarAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_IngresarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94))))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(lbl_bienvenido)
                .addGap(18, 18, 18)
                .addComponent(lbl_vamos)
                .addGap(39, 39, 39)
                .addComponent(lbl_usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_usuario_Administrador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_contraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_password_Administrador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_ingresarAdministrador)
                .addGap(18, 18, 18)
                .addComponent(btn_IngresarUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_password_AdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_password_AdministradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_password_AdministradorActionPerformed

    private void btn_IngresarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IngresarUsuarioActionPerformed

    }//GEN-LAST:event_btn_IngresarUsuarioActionPerformed

    private void btn_ingresarAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarAdministradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ingresarAdministradorActionPerformed

    private void btn_IngresarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_IngresarUsuarioMouseClicked
frm_sesion inicioCliente = new frm_sesion();
inicioCliente.setVisible(true);
this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_btn_IngresarUsuarioMouseClicked

    private void btn_ingresarAdministradorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ingresarAdministradorMouseClicked
  Usuario_Administrador admin = new Usuario_Administrador();
  
  String username = txt_usuario_Administrador.getText();
  String password = String.valueOf(txt_password_Administrador.getPassword());
  
  admin.tomarDatosDeBaseDeDatosEIniciarSesion(admin, username, password);
  
  if (admin.validarInicio(admin, username, password)){
      JOptionPane.showMessageDialog(null, "iniciando sesión");
  AdministradorControl menuAdmin = new AdministradorControl();
  menuAdmin.setVisible(true);
  this.dispose();
  }
  
  



        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ingresarAdministradorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Administrador_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Administrador_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Administrador_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Administrador_Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Administrador_Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_IngresarUsuario;
    private javax.swing.JButton btn_ingresarAdministrador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_bienvenido;
    private javax.swing.JLabel lbl_contraseña;
    private javax.swing.JLabel lbl_usuario;
    private javax.swing.JLabel lbl_vamos;
    private javax.swing.JPasswordField txt_password_Administrador;
    private javax.swing.JTextField txt_usuario_Administrador;
    // End of variables declaration//GEN-END:variables
}
