/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.g6_clienteservidorproyecto;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author brett
 */
public class frm_sesion extends javax.swing.JFrame {

    /**
     * Creates new form frm_sesion
     */
    public frm_sesion() {
        initComponents();
        getContentPane().setBackground(Color.white);
        this.setLocationRelativeTo(null);
        //inicie sesion con enter
        this.getRootPane().setDefaultButton(btn_IngresarAdministrador);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_bienvenido = new javax.swing.JLabel();
        lbl_vamos = new javax.swing.JLabel();
        btn_IngresarAdministrador = new javax.swing.JButton();
        lbl_imgCeleste = new javax.swing.JLabel();
        lbl_imgPersonas = new javax.swing.JLabel();
        lbl_usuario = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JTextField();
        lbl_contraseña = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        btn_ingresarClienteVIP = new javax.swing.JButton();
        btn_ingresarClienteRegular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_bienvenido.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_bienvenido.setText("Bienvenido");
        getContentPane().add(lbl_bienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 110, -1));

        lbl_vamos.setText("¡Vamos a ayudarlo a comprar repuestos para automóviles!");
        getContentPane().add(lbl_vamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        btn_IngresarAdministrador.setBackground(new java.awt.Color(0, 102, 204));
        btn_IngresarAdministrador.setForeground(new java.awt.Color(255, 255, 255));
        btn_IngresarAdministrador.setText("¿Ingresar como administrador?");
        btn_IngresarAdministrador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_IngresarAdministradorMouseClicked(evt);
            }
        });
        btn_IngresarAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IngresarAdministradorActionPerformed(evt);
            }
        });
        getContentPane().add(btn_IngresarAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 210, -1));

        lbl_imgCeleste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contains/Subtract.png"))); // NOI18N
        getContentPane().add(lbl_imgCeleste, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, -1, -1));

        lbl_imgPersonas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Contains/image 11.png"))); // NOI18N
        getContentPane().add(lbl_imgPersonas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        lbl_usuario.setText("Usuario");
        getContentPane().add(lbl_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));
        getContentPane().add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 230, 30));

        lbl_contraseña.setText("Contraseña");
        getContentPane().add(lbl_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 230, 30));

        btn_ingresarClienteVIP.setBackground(new java.awt.Color(0, 102, 204));
        btn_ingresarClienteVIP.setForeground(new java.awt.Color(255, 255, 255));
        btn_ingresarClienteVIP.setText("Ingresar como cliente VIP");
        btn_ingresarClienteVIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarClienteVIPActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ingresarClienteVIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 170, -1));

        btn_ingresarClienteRegular.setBackground(new java.awt.Color(0, 102, 204));
        btn_ingresarClienteRegular.setForeground(new java.awt.Color(255, 255, 255));
        btn_ingresarClienteRegular.setText("Ingresar como cliente regular");
        btn_ingresarClienteRegular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarClienteRegularActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ingresarClienteRegular, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 200, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordActionPerformed

    private void btn_IngresarAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IngresarAdministradorActionPerformed

   

    }//GEN-LAST:event_btn_IngresarAdministradorActionPerformed

    private void btn_ingresarClienteVIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarClienteVIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ingresarClienteVIPActionPerformed

    private void btn_IngresarAdministradorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_IngresarAdministradorMouseClicked
frm_Administrador_Inicio inicioAdmin = new frm_Administrador_Inicio();
inicioAdmin.setVisible(true);
this.dispose();


        // TODO add your handling code here:
    }//GEN-LAST:event_btn_IngresarAdministradorMouseClicked

    private void btn_ingresarClienteRegularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarClienteRegularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_ingresarClienteRegularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_sesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_IngresarAdministrador;
    private javax.swing.JButton btn_ingresarClienteRegular;
    private javax.swing.JButton btn_ingresarClienteVIP;
    private javax.swing.JLabel lbl_bienvenido;
    private javax.swing.JLabel lbl_contraseña;
    private javax.swing.JLabel lbl_imgCeleste;
    private javax.swing.JLabel lbl_imgPersonas;
    private javax.swing.JLabel lbl_usuario;
    private javax.swing.JLabel lbl_vamos;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
